import schedule
import time
import requests
import datetime
import json

class TradeAgent:
    def __init__(self, pushplus_token):
        self.pushplus_token = pushplus_token
        self.today_str = datetime.date.today().strftime("%Y-%m-%d")

    def fetch_youtuber_views(self):
        # 模擬抓取YouTube最新觀點 (實際環境可接入YouTube Data API)
        return """
### 第一部分：市場觀點掃描
> **YouTuber 核心觀點 (Top 5)**
• **付鵬的財經世界**：日圓貶值壓力與美債收益率高位震盪，全球宏觀流動性呈現結構性分化，需警惕新興市場匯率風險。
• **miula (M觀點)**：美股科技巨頭AI資本支出未見頂，算力與基礎設施仍是未來三季度唯一確定性增長主線。
• **財經M平方**：美國非農就業數據與通膨預期正在尋找新平衡，製造業PMI落底信號初現，有利週期股修復。
• **Blockworks Macro**：聯準會 (Fed) 降息預期一再延後，傳統宏觀資產與加密貨幣的聯動性正在重塑。
• **wally magazine**：港股處於歷史估值低位，南向資金的防禦性配置成為市場下行空間的最佳安全墊。

> **財經專業頻道分析 (Top 5)**
• **彭博社 (Bloomberg)**：亞洲市場外資流出放緩，中國資產的「便宜」特質吸引部分對沖基金進行均值回歸交易。
• **華爾街見聞**：A股政策面利好頻出，科创板及半导体設備獲國家大基金新一輪注資預期強烈。
• **CNBC**：全球供應鏈重組下，東南亞與墨西哥概念股熱度降溫，資金重回美國本土高科技板塊。
• **金十數據**：大宗商品（銅、金）在高位震盪，反映市場對地緣政治與通膨黏性的長期擔憂。
• **FT金融時報**：機構投資者對新興市場的態度由「減配」轉為「中性」，等待更明確的盈利拐點。
"""

    def fetch_market_sentiment(self):
        # 模擬抓取 moomoo, 高登網, Reddit 評論 (實際可使用BeautifulSoup, PRAW等)
        return """
---
### 第二部分：散戶與社群情緒監控
> **moomoo 實時市場掃描**
• **情緒熱度**：溫和看多。
• **焦點板塊**：AI 伺服器、高股息ETF。
• **散戶行為**：資金在科技股回調時呈現「越跌越買」特徵，對銀行/煤炭等防禦性板塊持倉穩定。

> **香港高登網 (HKGolden) 財經台**
• **情緒熱度**：極度謹慎。
• **主要觀點**：多數網民認為恒指近期的反彈屬於「挾淡倉」（熊市反彈），缺乏基本面強勢支撐；討論多集中於短線衍生品（牛熊證）博弈。

> **Reddit (r/stocks, r/investing)**
• **情緒熱度**：FOMO（錯失恐懼）與高處不勝寒並存。
• **主要觀點**：熱烈討論 NVDA、MSFT 等巨頭是否出現泡沫；對A/H股討論度極低，表明外資散戶資金尚未形成重返中國市場的共識。
"""

    def forecast_trend(self):
        return """
---
### 第三部分：量化因子與本週走勢預測
> **因子模型 (Factor Model) 輸出**
• **動量因子 (Momentum)**：A股科技板塊 > 港股互聯網 > A股消費。
• **價值因子 (Value)**：港股金融/地產估值極端偏低，修復動能累積。
• **流動性因子 (Liquidity)**：A股成交量溫和放大，港股流動性依然依賴南水。

> **本週走勢研判**
• **A股**：預計呈現「**震盪上行，板塊輪動**」格局。核心區間上移，科技成長與高股息將呈現蹺蹺板效應。
• **港股**：預計呈現「**底部抬升，遇阻回落**」特徵。估值修復行情延續，但面臨上方套牢盤壓力。
"""

    def fetch_capital_flow(self):
        return """
---
### 第四部分：南北向資金流向
> **港股通 (南向資金)**
• **現況**：持續呈「淨買入」態勢，日均淨流入規模維持在 30-50 億港元。
• **偏好**：集中於騰訊、美團等核心科網股，以及中移動、中海油等高股息央企。

> **滬深股通 (北向資金)**
• **現況**：呈現「雙向波動，微幅淨流出」。
• **偏好**：外資配置盤仍在觀望宏觀經濟數據，交易盤則在半導體與新能源之間做短線切換。
"""

    def macro_global_capital(self):
        return """
---
### 第五部分：全球現金流與大資本博弈
> **全球資金流向監測**
• **無風險收益**：美元流動性依然偏緊，大量資金囤積於美債及貨幣市場基金 (MMF)，享受 5% 左右的無風險收益。
• **風險資產**：增量資金高度集中於美國AI產業鏈，呈現顯著的「贏家通吃」效應。

> **大資本 (Smart Money) 思維回測**
• **核心邏輯**：「**啞鈴型策略 (Barbell Strategy)**」。
• **左端 (高防禦)**：重倉美債、黃金、以及中港市場的極低估值高股息資產，對沖宏觀衰退風險。
• **右端 (高爆發)**：不計估值買入全球最頂尖的AI算力與基礎設施龍頭，押注第四次工業革命。
• **結論**：大資本目前沒有進行全面性牛市配置的意圖，依然在確定性極高的兩極尋找避風港。
"""

    def divination_iching(self):
        # 簡單的易理生成，可以根據日期計算，此處為演示固定一卦
        return """
---
### 第六部分：周易八卦測算 (玄學量化輔助)
> **時局排盤**
• **測算時間**：丙午月 癸亥日 (2026年6月5日)。
• **本週卦象**：起卦得《**雷水解**》（震上坎下）。

> **易理推演**
• **卦辭**：解。利西南，無所往，其來復吉。有攸往，夙吉。
• **盤面解析**：「解」代表冰雪消融，困境緩解。震雷動於坎水之上，雷雨交加後撥雲見日。
• **金融映射**：象徵著市場前期的恐慌與流動性枯竭正在得到緩解（解套）。本週股市有震盪反彈、化險為夷之象。操作上宜順勢而為，遇急跌可低吸，不宜過度追高（無所往，其來復吉）。
"""

    def generate_report(self):
        report = f"# 麥肯錫式 AI 全景量化策略日報 ({self.today_str})\n"
        report += self.fetch_youtuber_views()
        report += self.fetch_market_sentiment()
        report += self.forecast_trend()
        report += self.fetch_capital_flow()
        report += self.macro_global_capital()
        report += self.divination_iching()
        
        # 結尾致詞
        report += "\n---\n*Generated by TradeAgent AI. Data refers to local time.*"
        return report

    def push_to_wechat(self, content):
        url = 'http://www.pushplus.plus/send'
        data = {
            "token": self.pushplus_token,
            "title": f"📈 AI 每日全景量化策略分析 ({self.today_str})",
            "content": content,
            "template": "markdown"
        }
        
        try:
            response = requests.post(url, data=json.dumps(data), headers={'Content-Type': 'application/json'})
            if response.status_code == 200:
                print(f"[{datetime.datetime.now()}] PushPlus 發送成功: {response.json()}")
            else:
                print(f"[{datetime.datetime.now()}] PushPlus 發送失敗: {response.status_code}")
        except Exception as e:
            print(f"發送異常: {e}")

def job():
    print(f"[{datetime.datetime.now()}] 開始生成今日研報並推送...")
    TOKEN = "26614f5b8a874aab9ad4791555079520"
    agent = TradeAgent(pushplus_token=TOKEN)
    report_content = agent.generate_report()
    agent.push_to_wechat(report_content)
    print(f"[{datetime.datetime.now()}] 任務完成。")

if __name__ == "__main__":
    # 若需立刻測試，可直接取消註解下一行
    # job()
    
    print("啟動 TradeAgent 定時任務，每天 12:00 PM 發送推送...")
    schedule.every().day.at("12:00").do(job)
    
    while True:
        schedule.run_pending()
        time.sleep(60)
